trigger:
  branches:
    include:
      - master
      - main

pr:
  branches:
    include:
      - master
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Replace with your Static Web App name
  staticWebAppName: 'EvalSummaryApp'
  # Replace with your resource group name
  resourceGroupName: 'AthenaDevelopmentWusRG'
  # Azure subscription service connection name
  azureSubscription: 'LocalEvalResources-MI-ServiceConnection'

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy to Azure Static Web Apps'
  condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  steps:
  - checkout: self
    submodules: true

  - task: NodeTool@0
    displayName: 'Setup Node.js'
    inputs:
      versionSpec: '18.x'

  - script: |
      npm install -g @azure/static-web-apps-cli
    displayName: 'Install Static Web Apps CLI'

  - script: |
      node build.js
    displayName: 'Build Application'

  - script: |
      echo "Built files in dist directory:"
      ls -la dist/
    displayName: 'List Built Files'

  - task: AzureStaticWebApp@0
    displayName: 'Deploy to Azure Static Web Apps'
    inputs:
      app_location: 'dist'
      api_location: ''
      output_location: ''
      azure_static_web_apps_api_token: '0444c9d136e2f3669a608b48a9e13e65e2e6107d84da71d471861cbc544cada603-9755d5a8-fce8-4d15-bcb6-35a4484c879301e242802359471e'
      action: 'upload'
      skip_app_build: true
      skip_api_build: true
